name: aproxy
version: 0.2.2
summary: Transparent proxy for HTTP and HTTPS/TLS connections.
description: |
  Aproxy is a transparent proxy for HTTP and HTTPS/TLS connections. By 
  pre-reading the Host header in HTTP requests and the SNI in TLS client 
  hellos, it forwards HTTP proxy requests with the hostname, therefore, 
  complies with HTTP proxies requiring destination hostname for auditing or
  access control.

license: Apache-2.0
base: core22
grade: stable
confinement: strict
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: amd64
    build-for: arm64

apps:
  aproxy:
    command: start-aproxy
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind

parts:
  aproxy:
    plugin: nil
    source: .
    build-snaps:
      - go
    override-build: |
      snapcraftctl build
      GOARCH=$SNAPCRAFT_TARGET_ARCH
      CGO_ENABLED=0
      go mod download
      go build -ldflags="-w -s"
      cp aproxy ${SNAPCRAFT_PART_INSTALL}/bin
  install-start-script:
    plugin: dump
    source: ./snap/local
    prime:
      - start-aproxy

hooks:
  configure: { }
