name: aproxy
version: 0.2.0
summary: Transparent proxy for HTTP and HTTPS/TLS connections.
description: |
  Aproxy is a transparent proxy for HTTP and HTTPS/TLS connections. By 
  pre-reading the Host header in HTTP requests and the SNI in TLS client 
  hellos, it forwards HTTP proxy requests with the hostname, therefore, 
  complies with HTTP proxies requiring destination hostname for auditing or
  access control.

license: Apache-2.0
base: core22
grade: stable
confinement: strict

apps:
  aproxy:
    command: start-aproxy
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind

parts:
  pollen:
    plugin: go
    source: .
    build-snaps:
      - go
  install-start-script:
    plugin: dump
    source: ./snap/local
    prime:
      - start-aproxy

hooks:
  configure: { }
