name: Publish

on:
  push:
    branches: [ main ]

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml

  publish:
    name: Publish Aproxy
    runs-on: ubuntu-latest
    needs: [ tests, integration-tests ]

    steps:
      - uses: actions/checkout@v2

      - name: Build Aproxy Snap
        id: snapcraft-build
        uses: snapcore/action-build@v1

      - name: Publish Aproxy
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: |
          for snap in aproxy*.snap
          do
            snapcraft upload $snap --release edge
          done
