name: Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish Aproxy
    runs-on: [ self-hosted, linux, x64, large ]

    steps:
      - uses: actions/checkout@v2

      - name: Build Aproxy Snap
        id: snapcraft-build
        uses: snapcore/action-build@v1

      - name: Upload Aproxy Snap
        uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.snapcraft-build.outputs.snap }}

      - name: Publish Aproxy
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.snapcraft-build.outputs.snap }}
          release: edge