name: Tests

on:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Ensure No Formatting Changes
        run: |
          go fmt ./...
          git diff --exit-code

      - name: Check Version Sync
        run: |
          bash .github/scripts/check-version-sync.sh

      - name: Check Version Bump For Go Changes
        run: |
          bash .github/scripts/check-go-version-bump.sh "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}"

      - name: Build and Test
        run: |
          go test -race ./...
